spring.application.name=worm


# Database Connection
spring.datasource.url=jdbc:postgresql://192.168.2.163:5432/worm
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
