spring.application.name=worm


# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/worm
spring.datasource.username=postgres
spring.datasource.password=m30w!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.config.import=optional:file:.env[.properties]